name: Perl checks

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl: ["5.14", "5.40"]
    name: Perl ${{ matrix.perl }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Perl and dependencies
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          install-modules-with: cpanm

      - name: Compile all Perl scripts
        run: prove --verbose t
